---
title: "ECON 8080 Course Material"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

- [Syllabus](syllabus.pdf)

# Homeworks

[HW 1](hw1.html), due Tuesday, Jan. 31, [[[solutions](hw1_sol.pdf)]]

[HW 2](hw2.html), due Thursday, Feb. 9, [[[solutions](hw2_sol.pdf)]]

- [cps09mar.dta](cps09mar.dta)

[HW 3](hw3.html), due Thursday, Mar. 2, [[[solutions](hw3_sol.pdf)]]

[HW 4](hw4.html), due Thursday, Mar. 23

# Additional Material for Midterm 1

* Midterm 1 covers the course lecture notes 1-4 / the first 4 chapters of Hansen.

* [Additional Practice Questions for Midterm 1](additional_practice1.html), these do not need to be turned in, [[[solutions](additional_practice1_sol.pdf)]]

# Course Material

We will cover the following topics:

(<span style="color: red; font-weight: bold;">Note:</span> Some of the material will be updated/expanded as we move through the semester.  Some of the topics at the end of the semester are tentative.)

0. [Introduction to R](introduction_to_R.html)

1. [Linear Regression](01_linear_regression.html)

<!--2. [Inference/Hypothesis Testing](02_hypothesis_testing.html)-->

2. [Resampling Methods](02_resampling_methods.html)

3. [Introduction to Nonlinear Models](03_nonlinear_models.html)

4. [Alternative Approaches to Causal Inference](04_alternative_causal_inference.html)

5. [Panel Data Approaches to Causal Inference](05_panel_data_causal_inference.html)

6. If we have time, an introduction to [Generalized Method of Moments]

7. If we have time, an introduction to [Quantile Regression]

8. If we have time, an introduction to [Nonparametric Regression]

# Slides

- First Week: [Introduction to ECON 8080](introduction_slides.html)

